### ISSUE TITLE
Improve UI of tool bar in smart view table views

### ISSUE THREAD

**Issue by anish-dfg** [anish-dfg/pantheon-ui#6]
The data-table.tsx component contains a toolbar with inconsistent spacing and it's overall design can be improved. The goals should be to

Improve the spacing between tool bar elements to make them consistent
Use icons (where possible) to minimize the space used by components where it is feasible, to bolster the ability of new tools to be added more easily.

**Comment by jenpennen** [comment]
I'll handle this.
